language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
# command to run tests
script: 
  - nosetests --with-coverage --cover-branches --cover-inclusive --cover-package=tzwhere
after_script:
  coveralls
